<?xml version="1.0" encoding="utf-8"?>
<Project>
    <ItemGroup Condition="'$(Platform)' == 'x64'">
        <PackageReference Include="chromiumembeddedframework.runtime.win-x64" PrivateAssets="all" />
        <PackageReference Include="cef.redist.osx64" PrivateAssets="all" />
        <PackageReference Include="cef.redist.linux64" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup Condition="'$(Platform)' == 'ARM64'">
        <PackageReference Include="chromiumembeddedframework.runtime.win-arm64" PrivateAssets="all" />
        <PackageReference Include="cef.redist.osx.arm64" PrivateAssets="all" />
        <PackageReference Include="cef.redist.linuxarm64" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
        <PackageReference Include="chromiumembeddedframework.runtime" PrivateAssets="all" />
    </ItemGroup>
</Project>
